name: CI

on:
  push:
    branches: [master, assignment-13]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Run ESLint (just checking for issues)
      - name: Run ESLint
        run: npm run lint

      # Run Prettier Check
      - name: Run Prettier Check
        run: npm run prettier:check

      # Run Tests
      - name: Run Tests
        run: npm test -- --watchAll=false
